# Generated by Django 5.1 on 2024-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria_nome', models.CharField(max_length=100)),
                ('auditoria_data', models.DateTimeField(auto_now=True)),
                ('auditoria_representante', models.CharField(max_length=100)),
                ('auditoria_cidade', models.CharField(max_length=100)),
                ('auditoria_analista', models.CharField(max_length=100)),
                ('auditoria_visitas_previstas', models.CharField(max_length=100)),
            ],
        ),
    ]
