# Generated by Django 5.1 on 2024-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tarefa_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
