# Generated by Django 5.1 on 2024-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_tarefa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='auditoria_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
