# Generated by Django 5.1 on 2024-09-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_auditoria_auditoria_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='auditoria_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tarefa_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
